version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.3.2
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.5.3

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/template.yml

  execute-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Debug SSH_PRIVATE_KEY
          command: echo "$SSH_PRIVATE_KEY"
      - run:
          name: Deploy CloudFormation Stack
          command: aws cloudformation deploy --template-file cloudformation/template.yml --stack-name lecture13-stack --capabilities CAPABILITY_NAMED_IAM --parameter-overrides MyKeyName=$SSH_PRIVATE_KEY

  execute-ansible:
    executor: ansible-playbook/default
    environment:
      ANSIBLE_CONFIG: ansible/ansible.cfg
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:GPLUelWsypK5BtBflkZZsGKf96FW5rzsSL1Tfv2aF28"
      - ansible-playbook/install:
          version: 2.10.7
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Set Environment Vars
          command: |
            set -x
            EC2_PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='EC2PublicIP'].OutputValue" --output text)
            AWS_S3_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
            CLOUDFRONT_DOMAIN=$(aws cloudformation describe-stacks --stack-name your-cloudfront-stack-name --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDomain'].OutputValue" --output text)
            echo "export AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}" >> $BASH_ENV
            echo "${EC2_PUBLIC_IP} ansible_connection=ssh ansible_user=ec2-user" > ansible/inventory.ini
            echo "export CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}" >> $BASH_ENV

            cat $BASH_ENV
            cat ansible/inventory.ini
#           AWS_ALB_DNS_NAME=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='ALBDNSName'].OutputValue" --output text)
#           echo "export AWS_ALB_DNS_NAME=${AWS_ALB_DNS_NAME}" >> $BASH_ENV
#           AWS_RDS_PASSWORD=$(aws secretsmanager get-secret-value --secret-id raisetech-rds-secret --query 'SecretString' --output text | jq -r '.password')
#           AWS_RDS_ENDPOINT=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='RDSEndpoint'].OutputValue" --output text)

#           echo "export AWS_RDS_PASSWORD=${AWS_RDS_PASSWORD}" >> $BASH_ENV
#           echo "export AWS_RDS_ENDPOINT=${AWS_RDS_ENDPOINT}" >> $BASH_ENV

      - run:
          name: Set Environment Vars
          command: |
            set -x
#           AWS_ALB_DNS_NAME=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='ALBDNSName'].OutputValue" --output text)
            EC2_PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='EC2PublicIP'].OutputValue" --output text)
            AWS_S3_BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
            CLOUDFRONT_DOMAIN=$(aws cloudformation describe-stacks --stack-name your-cloudfront-stack-name --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDomain'].OutputValue" --output text)
#           echo "export AWS_ALB_DNS_NAME=${AWS_ALB_DNS_NAME}" >> $BASH_ENV
            echo "export AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}" >> $BASH_ENV
            echo "${EC2_PUBLIC_IP} ansible_connection=ssh ansible_user=ec2-user" > ansible/inventory.ini
            echo "export CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}" >> $BASH_ENV

            cat $BASH_ENV
            cat ansible/inventory.ini
#            AWS_RDS_PASSWORD=$(aws secretsmanager get-secret-value --secret-id raisetech-rds-secret --query 'SecretString' --output text | jq -r '.password')
#            AWS_RDS_ENDPOINT=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='RDSEndpoint'].OutputValue" --output text)

#            echo "export AWS_RDS_PASSWORD=${AWS_RDS_PASSWORD}" >> $BASH_ENV
#            echo "export AWS_RDS_ENDPOINT=${AWS_RDS_ENDPOINT}" >> $BASH_ENV

      - run:
          name: Dump BASH_ENV
          command: cat $BASH_ENV
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook ansible/playbook.yml -i ansible/inventory.ini

  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: 3.2.3
      - add_ssh_keys:
          fingerprints:
            - "SHA256:GPLUelWsypK5BtBflkZZsGKf96FW5rzsSL1Tfv2aF28"
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Get EC2 Public IP
          command: |
            EC2_PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name lecture13-stack --query "Stacks[0].Outputs[?OutputKey=='EC2PublicIP'].OutputValue" --output text)
            echo "export EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $BASH_ENV
      - run:
          name: Set ~/.ssh/config
          command: |
            mkdir -p ~/.ssh
            echo "Host target" >> ~/.ssh/config
            echo "HostName ${EC2_PUBLIC_IP}" >> ~/.ssh/config
            echo "User ec2-user" >> ~/.ssh/config
            cat ~/.ssh/config
      # - run:
      #     name: Add rbenv init to .bashrc on EC2
      #     command: |
      #       ssh -o StrictHostKeyChecking=no target " 
      #         grep 'rbenv init' ~/.bashrc || echo 'export PATH="$HOME/.rbenv/bin:$PATH" && eval "$(rbenv init -)"' >> ~/.bashrc
      #       "
      - run:
          name: Setup Serverspec
          command: |
            cd serverspec
            bundle install
      - run:
          name: Debug Environment
          command: |
            echo "=== ENV ==="
            env | sort
            echo "=== EC2 IP ==="
            echo $EC2_PUBLIC_IP
            echo "=== SSH config ==="
            cat ~/.ssh/config
            echo "=== Spec files ==="
            find serverspec/spec
      - run:
          name: Execute Serverspec
          command: |
            cd serverspec
            bundle exec rspec --format documentation

workflows:
  lecture13-provisioning:
    jobs:
      - cfn-lint
      - execute-cfn:
          requires:
            - cfn-lint
      - execute-ansible:
          requires:
            - execute-cfn
      - execute-serverspec:
          requires:
            - execute-ansible
