version: 2.1

orbs:
  aws-cloudformation: circleci/aws-cloudformation@1.0.2
  ansible: circleci/ansible@1.0.0
  ruby: circleci/ruby@1.1.2

jobs:
  deploy:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cloudformation/deploy:
          stack-name: my-stack
          template: template.yml
          region: ap-northeast-1

  run-ansible:
    executor: ansible/default
    steps:
      - checkout
      - run:
          name: Set up SSH private key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i ansible/inventory ansible/playbook.yml

  run-serverspec:
    executor:
      name: ruby/default
      tag: '3.1.2'
    steps:
      - checkout
      - run:
          name: Set up SSH private key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Run ServerSpec tests
          command: |
            bundle exec rake spec

workflows:
  version: 2
  deploy-and-verify:
    jobs:
      - deploy
      - run-ansible:
          requires:
            - deploy
      - run-serverspec:
          requires:
            - run-ansible
