---
# tasks file for rvm

- name: Install dependencies for RVM and Ruby
  yum:
    name:
      # - curl
      - gnupg2
    state: present
  become: yes

- name: Import RVM GPG keys via keyserver
  shell: gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys \
      409B6B1796C275462A1703113804BB82D39DC0E3 \
      7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  args:
    executable: /bin/bash

- name: Clone rbenv
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: "/home/ec2-user/.rbenv"
    update: no
    version: master

- name: Add rbenv to PATH and initialize
  lineinfile:
    dest: "/home/ec2-user/.bash_profile"
    line: 'export PATH="/home/ec2-user/.rbenv/bin:$PATH" && eval "$(rbenv init -)"'
    create: yes
    state: present

- name: Create plugins directory
  file:
    path: "/home/ec2-user/.rbenv/plugins"
    state: directory
    mode: '0755'

- name: Clone ruby-build plugin
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"
    update: no

- name: Reload shell for rbenv (source .bash_profile)
  shell: "source /home/ec2-user/.bash_profile"
  args:
    executable: /bin/bash

- name: Set up rbenv environment variables and Install Ruby 3.2.3 with rbenv
  shell: |
    export PATH="/home/ec2-user/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv install -s 3.2.3
    rbenv global 3.2.3
  args:
    executable: /bin/bash

# - name: Add RVM repository
#   shell: curl -sSL https://get.rvm.io | bash -s stable
#   args:
#     creates: /home/ec2-user/.rvm/bin/rvm
#     executable: /bin/bash

